name: Flutter Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.5'  # Update as needed

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK (Release)
        run: flutter build apk --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: FutureAkhandRadio-APK
          path: build/app/outputs/flutter-apk/app-release.apk